const $=s=>document.querySelector(s);let invoices=JSON.parse(localStorage.getItem('lp_invoices')||'[]');let customers=JSON.parse(localStorage.getItem('lp_customers')||'[]');
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN'); const save=()=>{localStorage.setItem('lp_invoices',JSON.stringify(invoices));localStorage.setItem('lp_customers',JSON.stringify(customers));};
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#email').value==='admin@example.com'&&$('#password').value==='Admin@123'){localStorage.lp_auth='1';showApp()}else alert('Invalid admin credentials')};
function showApp(){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');renderAll()} if(localStorage.lp_auth==='1')showApp();
$('#logout').onclick=()=>{localStorage.removeItem('lp_auth');location.reload()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageTitle').textContent={dashboard:'Overview',customers:'Customers',invoice:'Create Invoice',invoices:'Invoices'}[p];renderAll()}
function renderAll(){let paid=invoices.filter(x=>x.status==='Paid'), pending=invoices.filter(x=>x.status==='Pending');$('#totalRevenue').textContent=money(paid.reduce((a,x)=>a+x.amount,0));let now=new Date(),mr=paid.filter(x=>{let d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((a,x)=>a+x.amount,0);$('#monthRevenue').textContent=money(mr);$('#pendingRevenue').textContent=money(pending.reduce((a,x)=>a+x.amount,0));$('#invoiceCount').textContent=invoices.length;
$('#recent').innerHTML=invoices.slice().reverse().slice(0,6).map(row).join('')||'<p class="muted">No invoices yet.</p>';$('#invoiceList').innerHTML=invoices.slice().reverse().map(row).join('')||'<p class="muted">No invoices yet.</p>';$('#customerList').innerHTML=customers.map(c=>`<div class="customer-row"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.business||'')} ${esc(c.phone||'')}</div></div><b>${money(invoices.filter(i=>i.customer===c.name).reduce((a,x)=>a+x.amount,0))}</b></div>`).join('')||'<p class="muted">No customers yet.</p>'}
function row(x){return `<div class="invoice-row"><div><b>${x.id}</b><div class="muted">${esc(x.customer)} · ${new Date(x.date).toLocaleDateString('en-IN')}</div></div><div><b>${money(x.amount)}</b> <span class="badge ${x.status.toLowerCase()}">${x.status}</span> <button class="ghost" onclick="preview('${x.id}')">View</button></div></div>`}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#invoiceForm').onsubmit=e=>{e.preventDefault();let x={id:'INV-'+Date.now().toString().slice(-6),date:new Date().toISOString(),customer:$('#customerName').value,business:$('#customerBusiness').value,phone:$('#customerPhone').value,service:$('#service').value,amount:Number($('#amount').value),status:$('#status').value,upi:$('#upi').value,note:$('#note').value};invoices.push(x);if(!customers.some(c=>c.name===x.customer))customers.push({name:x.customer,business:x.business,phone:x.phone});save();e.target.reset();renderAll();preview(x.id)};
function preview(id){let x=invoices.find(i=>i.id===id);$('#preview').innerHTML=`<div class="inv-head"><div><h2>INVOICE</h2><div class="muted">${x.id} · ${new Date(x.date).toLocaleDateString('en-IN')}</div></div><div><b>LedgerPro</b><div class="muted">Professional Billing</div></div></div><p><b>Bill to</b><br>${esc(x.customer)}<br>${esc(x.business)}<br>${esc(x.phone)}</p><hr><p><b>${esc(x.service)}</b><br><span class="muted">${esc(x.note)}</span></p><div class="total">${money(x.amount)}</div><div id="qrcode" class="qr"></div><p style="text-align:center" class="muted">Scan to pay via UPI<br>${esc(x.upi)}</p><span class="badge ${x.status.toLowerCase()}">${x.status}</span><button class="download" onclick="downloadPDF('${x.id}')">Download PDF</button>`;$('#modal').classList.remove('hidden');new QRCode($('#qrcode'),{text:`upi://pay?pa=${encodeURIComponent(x.upi)}&pn=LedgerPro&am=${x.amount}&cu=INR`,width:180,height:180})}
$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
function downloadPDF(id){let x=invoices.find(i=>i.id===id),{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(24);doc.text('INVOICE',20,25);doc.setFontSize(11);doc.text('LedgerPro — Professional Billing',20,34);doc.text(`Invoice: ${x.id}`,20,50);doc.text(`Date: ${new Date(x.date).toLocaleDateString('en-IN')}`,20,58);doc.text(`Customer: ${x.customer}`,20,75);doc.text(`Business: ${x.business||'-'}`,20,83);doc.line(20,92,190,92);doc.text(x.service,20,108);doc.text(`Total: ${money(x.amount)}`,20,125);doc.text(`Payment status: ${x.status}`,20,134);doc.text(`UPI: ${x.upi}`,20,145);doc.save(`${x.id}.pdf`)}
$('#addCustomerBtn').onclick=()=>{let n=prompt('Customer name?');if(n){customers.push({name:n,business:'',phone:''});save();renderAll()}};$('#search').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('#invoiceList .invoice-row').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'flex':'none')};
